### ISSUE TITLE
Facing Error bootstrap-validate.js:

### ISSUE THREAD

**Issue by sanjivsharmalv** [bootstrap-validate/bootstrap-validate#129]
Following is the error that I see in browser when I try using bootstrap-validate:
bootstrap-validate.js:1 Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at bootstrap-validate.js:1:16851
    at Array.forEach (<anonymous>)
    at M (bootstrap-validate.js:1:16787)
    at 7:176:13

**Comment by PascaleBeier** [comment]
Fixed in v2.3.0: missing selectors now warn and skip instead of throwing a null addEventListener error. Release: https://github.com/PascaleBeier/bootstrap-validate/releases/tag/v2.3.0 Usage docs: https://bootstrap-validate.js.org/v2/usage/
